import React, { useState, useEffect } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Legend, Cell } from 'recharts';
import { Settings, RefreshCw, BarChart3, Truck, Layers, Activity, BookOpen, Microscope, Calculator, Download } from 'lucide-react';
import { BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';
import './index.css';

// Material Cap Rolling Resistance Data (from paper scale tests)
const materialsData = [
  { name: 'Oil Sand Base', rr: 11, color: '#f59e0b' },
  { name: 'Sand Cap', rr: 18, color: '#ef4444' },
  { name: 'Pit Run Cap', rr: 9, color: '#3b82f6' },
  { name: 'Limestone Cap', rr: 6, color: '#10b981' },
];

function EquationFrame({ eyebrow, title, math, note, reference, accent = 'primary' }) {
  return (
    <div className={`equation-frame equation-frame-${accent}`}>
      {eyebrow ? <div className="equation-eyebrow">{eyebrow}</div> : null}
      {title ? <div className="equation-title">{title}</div> : null}
      <div className="equation-math">
        <BlockMath math={math} />
      </div>
      {note ? <p className="equation-note">{note}</p> : null}
      {reference ? <p className="equation-reference">{reference}</p> : null}
    </div>
  );
}

function EquationStep({ index, label, math, note, result, accent = 'primary' }) {
  return (
    <div className="equation-step">
      <div className="equation-step-header">
        <span className={`equation-step-index equation-step-index-${accent}`}>{index}</span>
        <div>
          <div className="equation-step-label">{label}</div>
          {note ? <p className="equation-step-note">{note}</p> : null}
        </div>
      </div>
      <div className="equation-step-body">
        <BlockMath math={math} />
      </div>
      {result ? <div className="equation-step-result">{result}</div> : null}
    </div>
  );
}

function App() {
  // Simulator State
  const [tireLoad, setTireLoad] = useState(900); // kN
  const [tireStiffness, setTireStiffness] = useState(13); // kN/mm
  const [groundStiffness, setGroundStiffness] = useState(4.5); // kPa/mm

  // Derived Advanced Geometric Boussinesq Calculations
  const phi = 3.84; // Typical tire diameter in meters
  const R = phi / 2; // Radius = 1.92m
  
  // Tire Deflection
  const deltaTireMeters = (tireLoad / tireStiffness) / 1000; 
  const tireDeflection = (deltaTireMeters * 1000); // in mm
  
  // --- METHOD A: Equivalent Linear Interaction Model ---
  const linearGroundDeflectionMm = (tireLoad / groundStiffness) * 0.15;
  const linearComputedRR = 2.0 + (linearGroundDeflectionMm * 0.2) + (tireDeflection * 0.05);

  // --- METHOD B: Joseph et al. (2017) geometric rolling resistance model ---
  // Eq. (5): footprint area generated by tire deformation
  const footprintArea = 1.35 * deltaTireMeters * phi;
  const footprintLength = 2 * Math.sqrt(Math.max(0, (phi * deltaTireMeters) - (deltaTireMeters ** 2)));
  const tireWidth = footprintLength > 0 ? footprintArea / footprintLength : 0;
  const footprintPressure = footprintArea > 0 ? tireLoad / footprintArea : 0; // kPa

  // Eq. (6): ground deformation using resilient pressure stiffness kp (kPa/mm)
  const deltaGroundMeters = footprintArea > 0 && groundStiffness > 0
    ? tireLoad / (footprintArea * groundStiffness * 1000)
    : 0;
  const groundDeflection = (deltaGroundMeters * 1000); // in mm

  // Eqs. (8)–(11): contact geometry
  const betaHalfSine = Math.max(0, Math.min(0.999999, footprintLength / phi));
  const beta = 2 * Math.asin(betaHalfSine);
  const lArcInner = Math.max(0, (betaHalfSine ** 2) + ((4 * deltaGroundMeters) / phi));
  const l_arc = 0.5 * phi * (Math.sqrt(lArcInner) - betaHalfSine);
  const alphaHalfSine = Math.max(0, Math.min(0.999999, l_arc / phi));
  const alpha = 2 * Math.asin(alphaHalfSine);
  const omega = l_arc > 0
    ? Math.asin(Math.max(0, Math.min(0.999999, deltaGroundMeters / l_arc)))
    : 0;
  const projectedLead = l_arc * Math.cos(omega);

  // Eq. (3): ground reaction offset y
  const leadingEdgeOffset = (0.5 * footprintLength) + projectedLead;
  const yNumerator = ((2 / 3) * (projectedLead ** 2) * deltaGroundMeters)
    + ((Math.PI / 8) * ((footprintLength + projectedLead) ** 3));
  const yDenominator = (projectedLead * deltaGroundMeters)
    + ((Math.PI / 4) * ((footprintLength + projectedLead) ** 2));
  const reactionOffset = yDenominator > 0
    ? leadingEdgeOffset - (yNumerator / yDenominator)
    : 0;

  // Eq. (1): rolling resistance as equivalent slope percentage
  const rollingResistance = (R - deltaTireMeters) > 0
    ? (reactionOffset / (R - deltaTireMeters)) * 100
    : 0;

  // Generates dummy GPS trace data for the RR distribution chart
  const [traceData, setTraceData] = useState([]);
  
  useEffect(() => {
    const data = [];
    for(let i=0; i<30; i++) {
      // Add suspension bounce solely to F_i (Tire Load) (~1Hz frequency + random noise)
      const bounce = Math.sin(i * 1.5) * (tireLoad * 0.1) + (Math.random() - 0.5) * (tireLoad * 0.05);
      const dynamicLoad = tireLoad + bounce;
      
      // Compute Method A: Linear dynamically
      const dynLinearGroundMm = (dynamicLoad / groundStiffness) * 0.15;
      const dynTireDeflection = (dynamicLoad / tireStiffness);
      let currentRRL = 2.0 + (dynLinearGroundMm * 0.2) + (dynTireDeflection * 0.05);
      
      // Compute Method B dynamically using Joseph et al. (2017), Eqs. (1), (3), (5), (6), and (8)–(11)
      const dynDeltaTireMeters = dynTireDeflection / 1000;
      const dynArea = 1.35 * dynDeltaTireMeters * phi;
      const dynLength = 2 * Math.sqrt(Math.max(0, (phi * dynDeltaTireMeters) - (dynDeltaTireMeters ** 2)));
      const dynWidth = dynLength > 0 ? dynArea / dynLength : 0;
      const dynDeltaGroundMeters = dynArea > 0 && groundStiffness > 0
        ? dynamicLoad / (dynArea * groundStiffness * 1000)
        : 0;

      const dynBetaHalfSine = Math.max(0, Math.min(0.999999, dynLength / phi));
      const dynLArcInner = Math.max(0, (dynBetaHalfSine ** 2) + ((4 * dynDeltaGroundMeters) / phi));
      const dynLArc = 0.5 * phi * (Math.sqrt(dynLArcInner) - dynBetaHalfSine);
      const dynOmega = dynLArc > 0
        ? Math.asin(Math.max(0, Math.min(0.999999, dynDeltaGroundMeters / dynLArc)))
        : 0;
      const dynProjectedLead = dynLArc * Math.cos(dynOmega);
      const dynLeadingEdgeOffset = (0.5 * dynLength) + dynProjectedLead;
      const dynYNumerator = ((2 / 3) * (dynProjectedLead ** 2) * dynDeltaGroundMeters)
        + ((Math.PI / 8) * ((dynLength + dynProjectedLead) ** 3));
      const dynYDenominator = (dynProjectedLead * dynDeltaGroundMeters)
        + ((Math.PI / 4) * ((dynLength + dynProjectedLead) ** 2));
      const dynY = dynYDenominator > 0
        ? dynLeadingEdgeOffset - (dynYNumerator / dynYDenominator)
        : 0;
      let currentRRB = (R - dynDeltaTireMeters) > 0
        ? (dynY / (R - dynDeltaTireMeters)) * 100
        : 0;
      
      // Clamp values slightly for visual aesthetics so they don't dip below 1%
      if (currentRRB < 1.0) currentRRB = 1.0;
      if (currentRRL < 1.0) currentRRL = 1.0;
      
      data.push({
        time: `T+${i}s`,
        rrBoussinesq: parseFloat(currentRRB.toFixed(2)),
        rrLinear: parseFloat(currentRRL.toFixed(2)),
        tireWidth: parseFloat(dynWidth.toFixed(3))
      });
    }
    setTraceData(data);
  }, [tireLoad, tireStiffness, groundStiffness]);

  const methodALinearEquation = 'RR\\% = 2.0 + \\left(\\delta_{ground} \\times 0.2\\right) + \\left(\\delta_{tire} \\times 0.05\\right)';
  const paperRollingResistanceEquation = 'RR\\% = 100\\left(\\frac{y}{\\left(\\frac{\\phi_{\\text{tire}}}{2} - \\delta_{\\text{tire}}\\right)}\\right)';

  const methodAEquations = [
    {
      index: '01',
      label: 'Tire Deflection',
      math: String.raw`\delta_{tire} = \frac{F_i}{k_{tire}} = \frac{${tireLoad}}{${tireStiffness}} = ${tireDeflection.toFixed(1)}\ \text{mm}`,
      note: 'Elastic tire compression from the wheel load and mapped tire stiffness.',
      result: `Compression = ${tireDeflection.toFixed(1)} mm`,
    },
    {
      index: '02',
      label: 'Equivalent Ground Deflection',
      math: String.raw`\delta_{ground} = \left(\frac{F_i}{k_p}\right)\times 0.15 = \left(\frac{${tireLoad}}{${groundStiffness}}\right)\times 0.15 = ${linearGroundDeflectionMm.toFixed(1)}\ \text{mm}`,
      note: 'A fast proportional map used for responsive field visualization.',
      result: `Ground sink = ${linearGroundDeflectionMm.toFixed(1)} mm`,
    },
    {
      index: '03',
      label: 'Linear Rolling Resistance',
      math: String.raw`RR\% = 2.0 + \left(${linearGroundDeflectionMm.toFixed(1)} \times 0.2\right) + \left(${tireDeflection.toFixed(1)} \times 0.05\right) = ${linearComputedRR.toFixed(2)}\%`,
      note: 'Baseline hard-surface resistance plus ground and tire deformation penalties.',
      result: `RR_linear = ${linearComputedRR.toFixed(2)}%`,
    },
  ];

  const methodBEquations = [
    {
      index: '01',
      label: 'Footprint Geometry',
      math: String.raw`A = 1.35\,\delta_{tire}\phi = ${footprintArea.toFixed(3)}\ \text{m}^2,\quad L = 2\sqrt{\phi\,\delta_{tire} - \delta_{tire}^2} = ${footprintLength.toFixed(3)}\ \text{m}`,
      note: 'The footprint area comes from Eq. (5). The base contact length L is derived from the circular chord geometry of the deflected tire.',
      result: `A = ${footprintArea.toFixed(3)} m², L = ${footprintLength.toFixed(3)} m`,
    },
    {
      index: '02',
      label: 'Effective Tire Width and Ground Deformation',
      math: String.raw`w = \frac{A}{L} = \frac{${footprintArea.toFixed(3)}}{${footprintLength.toFixed(3)}} = ${tireWidth.toFixed(3)}\ \text{m},\quad \delta_{ground} = \frac{F_i}{A\,k_p} = ${deltaGroundMeters.toFixed(3)}\ \text{m}`,
      note: 'Once L is known, the effective width follows directly from A = Lw. Eq. (6) then gives the resilient ground deformation.',
      result: `w = ${tireWidth.toFixed(3)} m, δ_ground = ${groundDeflection.toFixed(1)} mm`,
    },
    {
      index: '03',
      label: 'Lead Contact Geometry',
      math: String.raw`\begin{aligned}
        \omega &= ${((omega * 180) / Math.PI).toFixed(2)}^\circ,\quad
        \alpha = ${((alpha * 180) / Math.PI).toFixed(2)}^\circ,\quad
        \beta = ${((beta * 180) / Math.PI).toFixed(2)}^\circ \\
        l_{arc} &= \frac{\phi}{2}\left(\sqrt{\left(\frac{L}{\phi}\right)^2 + \frac{4\delta_{ground}}{\phi}} - \frac{L}{\phi}\right) \\
        &= \frac{${phi.toFixed(2)}}{2}\left(\sqrt{\left(\frac{${footprintLength.toFixed(3)}}{${phi.toFixed(2)}}\right)^2 + \frac{4(${deltaGroundMeters.toFixed(3)})}{${phi.toFixed(2)}}} - \frac{${footprintLength.toFixed(3)}}{${phi.toFixed(2)}}\right) \\
        &= ${l_arc.toFixed(3)}\ \text{m}
      \end{aligned}`,
      note: 'Eqs. (8), (9), (10), and the quadratic root in Eq. (11) define the leading-edge geometry of the tire-ground contact.',
      result: `ω = ${((omega * 180) / Math.PI).toFixed(2)}°, l_arc = ${l_arc.toFixed(3)} m`,
    },
    {
      index: '04',
      label: 'Ground Reaction Offset',
      math: String.raw`\begin{aligned}
        l_{arc}\cos\omega &= ${l_arc.toFixed(3)}\cos(${((omega * 180) / Math.PI).toFixed(2)}^\circ) = ${projectedLead.toFixed(3)}\ \text{m} \\
        y &= \left(\frac{1}{2}L + l_{arc}\cos\psi\right)
        - \frac{\frac{2}{3}\left(l_{arc}\cos\psi\right)^2\delta_{ground} + \frac{\pi}{8}\left(L + l_{arc}\cos\psi\right)^3}
        {\left(l_{arc}\cos\psi\right)\delta_{ground} + \frac{\pi}{4}\left(L + l_{arc}\cos\psi\right)^2} \\
        &= \left(\frac{1}{2}(${footprintLength.toFixed(3)}) + ${projectedLead.toFixed(3)}\right)
        - \frac{\frac{2}{3}(${projectedLead.toFixed(3)})^2(${deltaGroundMeters.toFixed(3)}) + \frac{\pi}{8}(${(footprintLength + projectedLead).toFixed(3)})^3}
        {(${projectedLead.toFixed(3)})(${deltaGroundMeters.toFixed(3)}) + \frac{\pi}{4}(${(footprintLength + projectedLead).toFixed(3)})^2} \\
        &= ${reactionOffset.toFixed(3)}\ \text{m}
      \end{aligned}`,
      note: 'Eq. (3) treats the pressure bulb as a triangularly ended hemispherical prism and computes the reaction offset y.',
      result: `y = ${reactionOffset.toFixed(3)} m`,
    },
    {
      index: '05',
      label: 'Rolling Resistance',
      math: String.raw`RR\% = 100\left(\frac{${reactionOffset.toFixed(3)}}{\left(\frac{${phi.toFixed(2)}}{2} - ${deltaTireMeters.toFixed(3)}\right)}\right) = ${rollingResistance.toFixed(2)}\%`,
      note: 'Eq. (1) converts the geometric offset into equivalent slope percent, which is how the paper reports rolling resistance.',
      result: `RR_paper = ${rollingResistance.toFixed(2)}%`,
    },
  ];

  return (
    <div className="layout">
      <header>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1rem' }}>
          <Truck size={48} color="var(--primary)" />
        </div>
        <h1>Haul Road <span className="text-gradient">Performance Simulator</span></h1>
        <p>
          Operational Methodologies for Rolling Resistance Evaluation.
          Interactive tooling estimating equivalent slope grade (%) based on hauler suspension, tire footprint, and resilient pressure stiffness.
        </p>
      </header>

      <div className="grid">
        {/* Left Column: Interactive Simulator */}
        <div className="glass-panel fade-in-up delay-1 calc-section">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
            <Settings color="var(--primary)" />
            <h2>Hauler & Surface Parameters</h2>
          </div>

          <div className="slider-group">
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <label>Tire Load (F) - kN</label>
              <span className="value-display">{tireLoad} kN</span>
            </div>
            <input 
              type="range" 
              min="500" 
              max="1500" 
              value={tireLoad}
              onChange={(e) => setTireLoad(parseInt(e.target.value))}
            />
          </div>

          <div className="slider-group">
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <label>Tire Effective Stiffness (k_tire) - kN/mm</label>
              <span className="value-display">{tireStiffness} kN/mm</span>
            </div>
            <input 
              type="range" 
              min="5" 
              max="25" 
              step="0.5"
              value={tireStiffness}
              onChange={(e) => setTireStiffness(parseFloat(e.target.value))}
            />
          </div>

          <div className="slider-group">
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <label>Resilient Ground Stiffness (k_p) - kPa/mm</label>
              <span className="value-display">{groundStiffness} kPa/mm</span>
            </div>
            <input 
              type="range" 
              min="1" 
              max="20" 
              step="0.5"
              value={groundStiffness}
              onChange={(e) => setGroundStiffness(parseFloat(e.target.value))}
            />
          </div>

          <div style={{ padding: '1rem', background: 'rgba(0,0,0,0.2)', borderRadius: '12px', marginTop: '1rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-around', alignItems: 'center' }}>
              <div>
                <div className="metric-label">Ground Rut (δ_ground)</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 600, color: 'var(--text-primary)', textAlign: 'center' }}>
                  {groundDeflection.toFixed(1)} mm
                </div>
              </div>
              <div style={{ width: '1px', height: '40px', background: 'var(--glass-border)' }}></div>
              <div>
                <div className="metric-label">Tire Flex (δ_tire)</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 600, color: 'var(--text-primary)', textAlign: 'center' }}>
                  {tireDeflection.toFixed(1)} mm
                </div>
              </div>
              <div style={{ width: '1px', height: '40px', background: 'var(--glass-border)' }}></div>
              <div>
                <div className="metric-label">Derived Width (w)</div>
                <div style={{ fontSize: '1.5rem', fontWeight: 600, color: 'var(--text-primary)', textAlign: 'center' }}>
                  {tireWidth.toFixed(2)} m
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Output Metrics & Real Time Chart */}
        <div className="glass-panel fade-in-up delay-2" style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <Activity color="var(--accent)" />
            <h2>Simulated Rolling Resistance</h2>
          </div>
          
          <div className="metric-big">
            {rollingResistance.toFixed(2)}%
          </div>
          <div className="metric-label">Equivalent Slope Grade</div>

          <div style={{ marginTop: 'auto' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
              <RefreshCw size={16} color="var(--text-secondary)"/>
              <h3 style={{ fontSize: '1rem', color: 'var(--text-secondary)' }}>Live Vehicle GPS Simulation</h3>
            </div>
            <div className="chart-container" style={{ height: '220px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={traceData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorRR_B" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="var(--primary)" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="var(--primary)" stopOpacity={0}/>
                    </linearGradient>
                    <linearGradient id="colorRR_L" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="var(--secondary)" stopOpacity={0.8}/>
                      <stop offset="95%" stopColor="var(--secondary)" stopOpacity={0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="time" stroke="var(--text-secondary)" fontSize={12} />
                  <YAxis stroke="var(--text-secondary)" fontSize={12} domain={['dataMin - 1', 'dataMax + 1']} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: 'var(--bg-accent)', borderColor: 'var(--glass-border)', color: 'var(--text-primary)' }}
                  />
                  <Area type="monotone" dataKey="rrBoussinesq" name="Paper Geometric Model" stroke="var(--primary)" fillOpacity={0.6} fill="url(#colorRR_B)" />
                  <Area type="monotone" dataKey="rrLinear" name="Linear Model" stroke="var(--secondary)" fillOpacity={0.6} fill="url(#colorRR_L)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      </div>

      {/* Theoretical Framework Panel */}
      <div className="glass-panel fade-in-up delay-3" style={{ marginTop: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.5rem' }}>
          <BookOpen color="var(--primary)" />
          <h2>Theoretical Framework</h2>
        </div>
        
        <div className="theory-grid">
          {/* Equation Box */}
          <div className="theory-card" style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
              <Calculator size={20} color="var(--accent)" />
              <h3 style={{ fontSize: '1.1rem', color: 'var(--text-primary)' }}>Key Geometric RR Equation</h3>
            </div>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', fontSize: '0.9rem', lineHeight: '1.5' }}>
              This section now keeps only the key rolling-resistance relation for each method. Method A shows the linear operational estimate, and Method B shows the paper’s Eq. (1).
            </p>
            <div className="equation-showcase">
              <EquationFrame
                eyebrow="Method A"
                title="Equivalent Linear Model"
                math={methodALinearEquation}
                note="Key relation for the fast operational estimate."
                reference="Reference: simulator operational heuristic implemented for responsive field visualization."
              />
              <EquationFrame
                eyebrow="Method B"
                title="Paper Geometric Model"
                math={paperRollingResistanceEquation}
                note="Key relation retained from the paper-based geometric implementation."
                reference="Reference: Joseph, T.G., Curley, M. & Anand, A. (2017), Eq. (1), Geotech Geol Eng 35, 2935-2946."
                accent="secondary"
              />
            </div>
            
          </div>

          {/* KPI Methods */}
          <div className="theory-card" style={{ padding: '1.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
              <Microscope size={20} color="var(--secondary)" />
              <h3 style={{ fontSize: '1.1rem', color: 'var(--text-primary)' }}>Parameter Determination</h3>
            </div>
            
            <div className="parameter-stack" style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <h4 style={{ color: 'var(--text-primary)', marginBottom: '0.25rem', fontSize: '0.95rem' }}>Resilient Ground Stiffness (k_p)</h4>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', lineHeight: '1.4', marginBottom: '0.75rem' }}>
                  Determined through an in-field <strong>Cyclic Plate Load Test</strong>. A plate is cyclically loaded directly onto the surface commensurate to a nominal 1g truck pressure until a resilient, constant cyclic deformation establishes an elastic equilibrium.
                </p>
                <a href="kp_determination_briefing.pdf" download style={{ textDecoration: 'none' }}>
                  <button className="primary theory-download-button" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem', padding: '8px 16px', background: 'rgba(59, 130, 246, 0.2)', color: 'var(--primary)', border: '1px solid var(--primary)', boxShadow: 'none' }}>
                    <Download size={16} />
                    Download PDF Protocol
                  </button>
                </a>
              </div>
              <div style={{ height: '1px', background: 'var(--glass-border)' }}></div>
              <div>
                <h4 style={{ color: 'var(--text-primary)', marginBottom: '0.25rem', fontSize: '0.95rem' }}>Effective Tire Stiffness (k_tire)</h4>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', lineHeight: '1.4', marginBottom: '0.75rem' }}>
                  Determined universally when a fully-loaded hauler rests stationary (1g condition). The inflation is mapped specifically such that each tire deforms by precisely <strong>7% diametral strain</strong> in sync with the nominal inflation specifications.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="glass-panel fade-in-up delay-3" style={{ marginTop: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '2rem' }}>
          <Layers color="var(--secondary)" />
          <h2>Wearing Course Material Comparison</h2>
        </div>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem', maxWidth: '800px' }}>
          Scale rolling resistance laboratory testing reveals that surface capping dramatically impacts haul truck rolling resistance. Sand caps tend to deteriorate and blend, worsening resistance, whereas crushed limestone optimally distributes load.
        </p>
        
        <div className="chart-container">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={materialsData} margin={{ top: 20, right: 30, left: 0, bottom: 5 }} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" horizontal={true} vertical={true} stroke="rgba(255,255,255,0.05)" />
              <XAxis type="number" stroke="var(--text-secondary)" domain={[0, 20]} />
              <YAxis dataKey="name" type="category" stroke="var(--text-primary)" fontSize={13} width={120} />
              <Tooltip 
                cursor={{fill: 'rgba(255,255,255,0.05)'}}
                contentStyle={{ backgroundColor: 'var(--bg-accent)', borderColor: 'var(--glass-border)', color: 'var(--text-primary)', borderRadius: '8px' }}
              />
              <Bar dataKey="rr" name="Rolling Resistance (%)" radius={[0, 8, 8, 0]} barSize={40}>
                {materialsData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="glass-panel fade-in-up delay-3" style={{ marginTop: '2rem' }}>
        <div className="method-comparison-window method-comparison-window-full">
          <div className="method-comparison-header">
            <div>
              <div className="method-comparison-eyebrow">Method Comparison</div>
              <h4 className="method-comparison-title">Parallel Method View</h4>
            </div>
            <p className="method-comparison-note">
              Each method stays in its own vertical lane so the derivations can be compared side by side at full width.
            </p>
          </div>

          <div className="theory-methods-grid">
            <div className="theory-method-card theory-method-card-primary" style={{ background: 'rgba(0,0,0,0.15)', border: '1px solid var(--glass-border)', padding: '1rem', borderRadius: '8px', fontSize: '0.85rem', color: 'var(--text-primary)' }}>
              <div className="theory-method-heading">
                <strong style={{color:'var(--accent)', fontSize:'0.95rem'}}>Method A: Equivalent Linear Model</strong>
                <span className="theory-method-summary">Fast operational estimate for field-facing dashboards.</span>
              </div>
              <div className="equation-step-list">
                {methodAEquations.map((step) => (
                  <EquationStep key={step.index} {...step} accent="primary" />
                ))}
              </div>
            </div>

            <div className="theory-method-card theory-method-card-secondary" style={{ background: 'rgba(0,0,0,0.15)', border: '1px solid var(--glass-border)', padding: '1rem', borderRadius: '8px', fontSize: '0.85rem', color: 'var(--text-primary)' }}>
              <div className="theory-method-heading">
                <strong style={{color:'var(--accent)', fontSize:'0.95rem'}}>Method B: Paper Geometric Model</strong>
                <span className="theory-method-summary">Implemented from Joseph, Curley, and Anand (2017), using Eqs. 1, 3, 5, 6, and 8-11.</span>
              </div>
              <div className="equation-step-list">
                {methodBEquations.map((step) => (
                  <EquationStep key={step.index} {...step} accent="secondary" />
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="footer">
        <div style={{ fontSize: '0.85rem', marginTop: '1.5rem', opacity: 0.9, background: 'rgba(0,0,0,0.2)', padding: '1.5rem', borderRadius: '12px', border: '1px solid var(--glass-border)', maxWidth: '600px', margin: '1.5rem auto 0 auto' }}>
          <p style={{ fontWeight: '600', marginBottom: '0.5rem', color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: '1px', fontSize: '0.75rem' }}>Scientific Reference</p>
          <p style={{ lineHeight: '1.5' }}>
            Joseph, T.G., Curley, M. & Anand, A. <em>Operational Methodologies for Rolling Resistance Evaluation.</em> Geotech Geol Eng 35, 2935–2946 (2017).
          </p>
          <a href="https://doi.org/10.1007/s10706-017-0292-y" target="_blank" rel="noreferrer" style={{ color: 'var(--accent)', textDecoration: 'underline', display: 'inline-block', marginTop: '0.5rem' }}>
            https://doi.org/10.1007/s10706-017-0292-y
          </a>
        </div>
      </footer>
    </div>
  );
}

export default App;
